### ISSUE TITLE
It seems SCFpyr_mod class has something wrong

### ISSUE THREAD

**Issue by wbhu** [t-fukiage/hiddenstereo#1]
Thanks for your great work. But the SCFpyr_mod class has no implementation of the method "reconSFpyr", which is called in line224 in ppt_ext.py. Could you please give me some advice.

Thanks a lot

**Comment by t-fukiage** [comment]
SCFpyr_mod class overrides SFpyr class in pyPyrTools, and reconSFpyr method is defined in SFpyr class. Please make sure that pyPyrTools (https://github.com/LabForComputationalVision/pyPyrTools) is correctly installed.
Thank you.

**Comment by wbhu** [comment]
Thanks for your help.
